version: '3.0'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hw-new
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=masterkey
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    # networks:
    #   - database-network
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masterkey
    networks:
      database-network:
        aliases:
          - db


networks:
  database-network:
    driver: bridge
    external: false